#############################################################################
# Makefile for building: vfds.app/Contents/MacOS/vfds
# Generated by qmake (3.1) (Qt 6.1.3)
# Project:  vfds.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile vfds.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang -F/usr/local/Cellar/qt/6.1.3/lib
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = vfds1.0.0
DISTDIR = /Users/jaredmay/Capstone/vfds/.tmp/vfds1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/usr/local/Cellar/qt/6.1.3/lib
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/6.1.3/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/BackgroundData.cpp \
		src/CTReader.cpp \
		src/Fracture.cpp \
		src/ImageDataClass.cpp \
		src/ImageProcessor.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/PartData.cpp \
		src/Split.cpp \
		src/Voxel.cpp moc_mainwindow.cpp
OBJECTS       = BackgroundData.o \
		CTReader.o \
		Fracture.o \
		ImageDataClass.o \
		ImageProcessor.o \
		main.o \
		mainwindow.o \
		PartData.o \
		Split.o \
		Voxel.o \
		moc_mainwindow.o
DIST          = /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/lex.prf \
		vfds.pro src/BackgroundData.h \
		src/CTReader.h \
		src/Fracture.h \
		src/ImageDataClass.h \
		src/ImageProcessor.h \
		src/mainwindow.h \
		src/PartData.h \
		src/Split.h \
		src/Voxel.h \
		test/catch.hpp src/BackgroundData.cpp \
		src/CTReader.cpp \
		src/Fracture.cpp \
		src/ImageDataClass.cpp \
		src/ImageProcessor.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/PartData.cpp \
		src/Split.cpp \
		src/Voxel.cpp
QMAKE_TARGET  = vfds
DESTDIR       = 
TARGET        = vfds.app/Contents/MacOS/vfds

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 11.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/jaredmay/Capstone/vfds/.qmake.stash
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/jaredmay/Capstone/vfds/vfds.pro


include /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

vfds.app/Contents/MacOS/vfds:  $(OBJECTS)  
	@test -d vfds.app/Contents/MacOS/ || mkdir -p vfds.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vfds.pro /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources_functions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/lex.prf \
		vfds.pro \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Resources/QtGui.prl \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile vfds.pro
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_coap_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_tools_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources_functions.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/lex.prf:
vfds.pro:
/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Resources/QtGui.prl:
/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile vfds.pro

qmake_all: FORCE

vfds.app/Contents/PkgInfo: 
	@test -d vfds.app/Contents || mkdir -p vfds.app/Contents
	@$(DEL_FILE) vfds.app/Contents/PkgInfo
	@echo "APPL????" > vfds.app/Contents/PkgInfo
vfds.app/Contents/Resources/empty.lproj: 
	@test -d vfds.app/Contents/Resources || mkdir -p vfds.app/Contents/Resources
	@touch vfds.app/Contents/Resources/empty.lproj
	
vfds.app/Contents/Info.plist: 
	@test -d vfds.app/Contents || mkdir -p vfds.app/Contents
	@$(DEL_FILE) vfds.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.vfds,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.vfds,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,vfds,g" -e "s,@LIBRARY@,vfds,g" -e "s,\$${EXECUTABLE_NAME},vfds,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang/Info.plist.app >vfds.app/Contents/Info.plist

all: Makefile \
		vfds.app/Contents/PkgInfo \
		vfds.app/Contents/Resources/empty.lproj \
		vfds.app/Contents/Info.plist vfds.app/Contents/MacOS/vfds

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/BackgroundData.h src/CTReader.h src/Fracture.h src/ImageDataClass.h src/ImageProcessor.h src/mainwindow.h src/PartData.h src/Split.h src/Voxel.h test/catch.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/BackgroundData.cpp src/CTReader.cpp src/Fracture.cpp src/ImageDataClass.cpp src/ImageProcessor.cpp src/main.cpp src/mainwindow.cpp src/PartData.cpp src/Split.cpp src/Voxel.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r vfds.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: src/mainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QAction \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QtGui \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiglobal.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstractfileiconprovider.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessible.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbackingstore.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbitmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbrush.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qclipboard.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolorspace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolortransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdesktopservices.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdrag.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qeventpoint.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontdatabase.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontinfo.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontmetrics.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericmatrix.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qglyphrun.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qguiapplication.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengineplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimageiohandler.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagereader.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagewriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputmethod.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qkeysequence.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmovie.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qoffscreensurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopengl.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglcontext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagelayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpageranges.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagesize.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainterpath.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpdfwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpicture.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixelformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmapcache.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpointingdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpolygon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qquaternion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrasterwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrawfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qregion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgb.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgba64.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsessionmanager.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qshortcut.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstatictext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstylehints.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocument.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlist.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextoption.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtexttable.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundogroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundostack.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvalidator.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector2d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector3d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector4d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvectornd.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindowdefs.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiversion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/Qt \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qnamespace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qfiledialog.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/6.1.3/share/qt/libexec/moc
	/usr/local/Cellar/qt/6.1.3/share/qt/libexec/moc $(DEFINES) --include /Users/jaredmay/Capstone/vfds/moc_predefs.h -I/usr/local/Cellar/qt/6.1.3/share/qt/mkspecs/macx-clang -I/Users/jaredmay/Capstone/vfds -I/Users/jaredmay/Capstone/vfds -I/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/usr/local/Cellar/qt/6.1.3/lib src/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

BackgroundData.o: src/BackgroundData.cpp src/BackgroundData.h \
		src/ImageDataClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BackgroundData.o src/BackgroundData.cpp

CTReader.o: src/CTReader.cpp src/CTReader.h \
		src/Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CTReader.o src/CTReader.cpp

Fracture.o: src/Fracture.cpp src/Fracture.h \
		src/Voxel.h \
		src/Split.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fracture.o src/Fracture.cpp

ImageDataClass.o: src/ImageDataClass.cpp src/ImageDataClass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageDataClass.o src/ImageDataClass.cpp

ImageProcessor.o: src/ImageProcessor.cpp src/ImageProcessor.h \
		src/Split.h \
		src/Voxel.h \
		src/Fracture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageProcessor.o src/ImageProcessor.cpp

main.o: src/main.cpp /usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qapplication.h \
		src/mainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QAction \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QtGui \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiglobal.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstractfileiconprovider.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessible.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbackingstore.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbitmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbrush.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qclipboard.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolorspace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolortransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdesktopservices.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdrag.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qeventpoint.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontdatabase.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontinfo.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontmetrics.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericmatrix.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qglyphrun.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qguiapplication.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengineplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimageiohandler.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagereader.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagewriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputmethod.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qkeysequence.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmovie.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qoffscreensurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopengl.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglcontext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagelayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpageranges.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagesize.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainterpath.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpdfwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpicture.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixelformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmapcache.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpointingdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpolygon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qquaternion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrasterwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrawfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qregion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgb.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgba64.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsessionmanager.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qshortcut.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstatictext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstylehints.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocument.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlist.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextoption.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtexttable.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundogroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundostack.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvalidator.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector2d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector3d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector4d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvectornd.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindowdefs.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiversion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/Qt \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qnamespace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qfiledialog.h \
		src/Split.h \
		src/Voxel.h \
		src/ImageProcessor.h \
		src/Fracture.h \
		src/CTReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qapplication.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenu \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenu.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMenuBar \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmenubar.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QAction \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaction.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QGridLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qgridlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/QtGui \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiglobal.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstractfileiconprovider.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessible.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qactiongroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbackingstore.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbitmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qbrush.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qclipboard.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolorspace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcolortransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdesktopservices.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qdrag.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qeventpoint.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfilesystemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontdatabase.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontinfo.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qfontmetrics.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericmatrix.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qglyphrun.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qguiapplication.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qicon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qiconengineplugin.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimage.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimageiohandler.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagereader.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qimagewriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qinputmethod.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qkeysequence.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qmovie.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qoffscreensurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopengl.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglcontext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglextrafunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qopenglfunctions.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagelayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpageranges.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpagesize.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpaintengine.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpainterpath.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpdfwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpicture.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixelformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmap.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpixmapcache.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpointingdevice.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qpolygon.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qquaternion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrasterwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrawfont.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qregion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgb.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qrgba64.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qscreen.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsessionmanager.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qshortcut.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstatictext.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qstylehints.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurface.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsurfaceformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextcursor.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocument.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextformat.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlayout.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextlist.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextobject.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtextoption.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtexttable.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtransform.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundogroup.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qundostack.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvalidator.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector2d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector3d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvector4d.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qvectornd.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindow.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qwindowdefs.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtGui.framework/Headers/qtguiversion.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/Qt \
		/usr/local/Cellar/qt/6.1.3/lib/QtCore.framework/Headers/qnamespace.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QScrollArea \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qscrollarea.h \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/QFileDialog \
		/usr/local/Cellar/qt/6.1.3/lib/QtWidgets.framework/Headers/qfiledialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

PartData.o: src/PartData.cpp src/PartData.h \
		src/ImageDataClass.h \
		src/Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PartData.o src/PartData.cpp

Split.o: src/Split.cpp src/Split.h \
		src/Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Split.o src/Split.cpp

Voxel.o: src/Voxel.cpp src/Voxel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Voxel.o src/Voxel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

